spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:weatherdb
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
resilience4j:
  ratelimiter:
    instances:
      basic:
        limit-for-period: 10
        limit-refresh-period: 1m
        timeout-duration: 10s
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
          - prometheus
weather-stack:
  api-url: http://api.weatherstack.com/current
  api-key: ${WEATHER_STACK_API_KEY:41658e0e90750cbd06bbe14a1af032ac}
  api-call-limit: 30
  cache-name: weather
  cache-ttl: 10000
